name: user_repository
description: The Repo that handles users
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2

  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
